name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: terraform init

    - name: Terraform Plan
      env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: terraform plan

    - name: Terraform Apply
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
